### ISSUE TITLE
File Browser not rendering using swagger 3 version

### ISSUE THREAD

**Issue by prasad1007** [LalithK90/Swagger3-Documentation-Springboot-Sample#2]
Hi there, I tried this source code and added below sample endpoint but swagger not recognised file browser and not showing it on UI. is there any other special config we need to enable it? thanks

@PostMapping(
      value = "load",
      produces = {MediaType.APPLICATION_JSON_VALUE},
      consumes = {MediaType.MULTIPART_FORM_DATA_VALUE})
  public ResponseEntity<FileProcessingResponse> load(
      @RequestParam final Stage stage,
      @RequestParam final MultipartFile file)

**Comment by LalithK90** [comment]
Yap

1. First add a dependency in build.gradle file or pom.xml while doing that find relevant dependency

2. add those code to your project and try to view.

**Comment by prasad1007** [comment]
Hi Lalith,

I have tried all dependencies out there and also hut of a code, can you please tell me exact dependency and code to add here. For me issue is swagger is not showing file picker on UI for Multipart File object. Thanks

**Comment by LalithK90** [comment]
Did u try to upload a file with relation on 
```

@PostMapping(
value = "load",
produces = {MediaType.APPLICATION_JSON_VALUE},
consumes = {MediaType.MULTIPART_FORM_DATA_VALUE})
public ResponseEntity load(
@RequestParam final Stage stage,
@RequestParam final MultipartFile file)
```

1. What is this **Stage** object is this?

2. Is this **Multipart** belongs to **Stage**?


However, I created a sample code to resolve your issue plz check `**StageController.java** `

![image](https://user-images.githubusercontent.com/27762514/99913865-1174c200-2d20-11eb-8f8b-1c12dde15612.png)


Thanks

Lalith

**Comment by prasad1007** [comment]
Still not working for me as expected, tried below:

import io.swagger.v3.oas.annotations.parameters.RequestBody;

@PostMapping(
      value = "load")
  public ResponseEntity<FileProcessingResponse> load(
      @RequestBody final MultipartFile file)

Deps i am using

<dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-boot-starter</artifactId>
            <version>3.0.0</version>
        </dependency>

In swagger config i am using @EnableSwagger2
UI shows:

![image](https://user-images.githubusercontent.com/14856931/99920321-9957cd80-2d1a-11eb-943c-6f9c9ef5b311.png)

any idea?

**Comment by LalithK90** [comment]
Remove that `@EnableSwagger2`
```

@PostMapping(
value = "load")
public ResponseEntity load(
@requestbody final MultipartFile file)
```
`@requestbody final MultipartFile file` -> change to `@RequestParam final MultipartFile file`
